# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# this breaks the build
# https://github.com/issmirnov/zmk-config/runs/2156224108?check_suite_focus=true
# CONFIG_ZMK_DISPLAY=y
